import Sidebar from "@/components/sidebar";
import { RootProvider } from "@/providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Solar Info",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider>
          <div className="flex w-full h-screen bg-slate-50">
            <Sidebar />
            <div className="flex flex-col flex-1 w-full">
              <main className="h-full lg:overflow-y-auto">
                <div className="relative w-full h-screen bg-slate-50 p-3 ">
                  {children}
                </div>
              </main>
            </div>
          </div>
        </RootProvider>
      </body>
    </html>
  );
}
